### ISSUE TITLE
There is no npm package

### ISSUE THREAD

**Issue by sadicann** [beyonk-adventures/sapper-rbac#2]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@beyonk%2fsapper-rbac - Not found
npm ERR! 404
npm ERR! 404  '@beyonk/sapper-rbac@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by sadicann** [comment]
I installed with `npm install https://github.com/beyonk-adventures/sapper-rbac.git --save`

**Comment by antony** [comment]
@sadicann The installation instructions are in the README. You need:

`npm install --save-dev @beyonk/sapper-rbac`

**Comment by sadicann** [comment]
https://prnt.sc/rxakjw
