### ISSUE TITLE
Err: routeInfo is undefined

### ISSUE THREAD

**Issue by sadicann** [beyonk-adventures/sapper-rbac#4]
Working well but there is an error in developer console
https://prnt.sc/rxb1yo

**Comment by antony** [comment]
This is because you are visiting a route which doesn't match any of your rules.

I would suggest that you add a catchall route as per the docs, but I will leave this issue open so that I can add a console message to help developers in this instance.

**Comment by khalld** [comment]
I have the same problem, in my project "/" is the index of the app.
But if i put `unrestrict("/.*")` I lose all the rules set because the rest of the routes are, for example, `'/admin/panel'` or `'/admin/profile'`.
Any suggestion?

**Comment by antony** [comment]
@khalld put the catchall last

**Comment by khalld** [comment]
Still not working.
This is my-routes file

```
.unrestrict('/nopermission.*')
    .restrict('/admin/admin.*', ['admin'])
    .restrict('/admin/page1.*', ['admin','user1'])
    .restrict('/admin/settings.*', ['admin','user1'])
    .restrict('/admin/page2.*', ['admin','user2'])
    .restrict('/admin/profile.*',['admin','user1','user2'])
    .restrict('/admin.*',['admin','user1','user2'])
    .unrestrict('/.*')
    .build()
```

It redirect me in to nopermission page.
