### ISSUE TITLE
`<Routes> was created with unknown prop 'user'` warning?

### ISSUE THREAD

**Issue by davidhund** [beyonk-adventures/sapper-rbac#5]
As a Svelte n00b I am very thankful for your work providing an 'auth example' and this RBAC lib 🙏🏻

I am currently trying to implement it with a back-end API providing session cookies with a JWT. 
It seems I am almost there but now I notice these warnings in the console:

```
<Routes> was created with unknown prop 'user'
```

Looking into this Warning it seems it's not a big issue. But I cannot figure out _where_ it originates from and _what_ to do about it 😅

Where is this `<Routes>` component initialized and how (if at all) should I initialize it with a `user` prop?

**Update 15-06** I cannot figure out what exactly 'fixed' this but the warning is gone after some refactoring… Leaving the issue open for now.

**Comment by antony** [comment]
`Routes` isn't a component of this repository, so it's nothing to do with us :)

Sounds like whatever router you're using :)
